config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  resources :foods
  resources :recipe_foods

  resources :recipes, except: :edit do
    member do
      patch 'toggle_public'
    end
    resources :recipe_foods, only: %i[new create destroy]
  end 

  resources :shopping_lists, only: [:index] do
    get :generate, on: :collection
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { minimun: 2, maximun: 50 }, allow_blank: false
  validates :measurement_unit, presence: true, allow_blank: false
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_than: 0 }

  def total_price
    food.price * quantity
  end

  def quantity_needed
    quantity - food.quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes, dependent: :destroy, foreign_key: 'user_id'
  has_many :foods, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show destroy]
  before_action :authenticate_user!
  def index
    @foods = Food.where(user_id: current_user.id)
  end

  def show
    # show
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id
    if @food.save
      redirect_to foods_path, notice: 'Add new food'
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path, notice: 'food was successfully deleted.'
  end

  private

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.includes(:recipe_foods).where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    puts params[:recipe_id]
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new
  end

  def create
    @recipe = Recipe.find(params[:format])
    @recipe_food = @recipe.recipe_foods.new(recipe_foods_params)

    if @recipe_food.save
      redirect_to recipe_path(@recipe), notice: 'Add new ingredient'
    else
      redirect_to new_recipe_recipe_food_path(@recipe.id)
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy!

    redirect_to recipe_path(@recipe.id), notice: 'Ingredient successfully deleted'
  end

  private

  def recipe_foods_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show destroy]
  before_action :authenticate_user!

  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def show
    # show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to recipes_path, notice: 'Add new recipe'
    else
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe was successfully deleted.'
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    render json: { public: @recipe.public }
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def index
    recipe_id = params[:recipe_id]
    return unless recipe_id.present?

    @recipe = Recipe.includes(:recipe_foods).find(recipe_id)
    @recipe_foods = @recipe.recipe_foods
    @total_amount = 0
    @shopping_list = []
    @foods = current_user.foods
    @foods.each do |food|
      available_quantity = food.quantity
      required_quantity = RecipeFood.where(food_id: food.id).sum(:quantity)
      quantity_needed = available_quantity - required_quantity
      list = {}
      list['name'] = food.name
      list['quantity'] = quantity_needed
      list['price'] = quantity_needed * food.price
      @shopping_list.push(list)

      @total_amount += list['price']
    end
  end

  def generate
    recipe_id = params[:recipe_id]
    redirect_to shopping_lists_path(recipe_id:)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/index.html.erb
<div class="container">
    <div class="d-flex justify-content-between items-center mb-4">
      <h2>Foods</h2>
      <%= link_to 'Add New Food', new_food_path, class: 'btn btn-primary' %>
    </div>



        <table class="table table-bordered table-striped table-hover">
            <thead>
                <th>Food</th>
                <th>Measurement Unit</th>
                <th>Unit Price($)</th>
                <th>Actions</th>
            </thead>

            <tbody>
            
            <% @foods.each do |food|%>
             <tr class="">
    
              <td> <%= link_to controller: 'foods', action: 'show', id: food.id do %><%= food.name %><% end %></td>
              <td ><%= food.measurement_unit %></td>
              <td><%= food.price %></td>
              <td>
                <% if current_user.id  === food.user_id %>
                  <%= link_to 'Delete Food', food_path(food), data: {turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this food?'}, class: 'btn btn-primary' %>
                <% end %>
              </td>
      
            </tr>

           <% end %>
            
            </tbody>
        </table>




  </div>
  

app/views/foods/new.html.erb
<div class="container">
     <h2 class="mb-4">New Food</h2>
        <%= form_with model: @food, url: foods_path, class: "form" do |f| %>
                <div class="row">
                  <div class="col-md-7 mb-3">
                    <div class="form-group">
                      <%= f.label :name %><br />
                      <%= f.text_field :name, autofocus: true, autocomplete: "name",  class: "form-control form-control-lg" %>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-7 mb-3">
                  <div class="row">
                  <div class="col-md-6 mb-3">
                    <div class="form-group">
                      <%= f.label :measurement_unit %><br />
                      <%= f.text_field :measurement_unit, autofocus: true, autocomplete: "measurement_unit",  class: "form-control form-control-lg" %>
                    </div>
                  </div>
                  <div class="col-md-6 mb-3">
                    <div class="form-group">
                      <%= f.label :price %><br />
                      <%= f.text_field :price, autofocus: true, autocomplete: "price",  class: "form-control form-control-lg" %>
                    </div>
                  </div>
                </div>
                </div>
                </div>
                
                <div class="row">
                    <div class="col-md-7 mb-3">
                        <div class="form-group">
                            <%= f.label :quantity %><br />
                            <%= f.number_field :quantity, autofocus: true, autocomplete: "quantity",  class: "form-control form-control-lg" %>
                        </div>
                    </div>
                </div>

                <div class="actions py-4">
                  <%= f.submit 'Submit', class: 'btn btn-primary' %>
                </div>
        <% end %>
  </div>

app/views/foods/show.html.erb
<div class="container">
    <h2 class="mb-4"><%= @food.name %></h2>
    <h5>Quantity :<%= @food.quantity %></h5>
    <h5>Measurement unit : <b><%= @food.measurement_unit %></b></h5>
    <h5>Price : <b><%= @food.price %></b></h5>
</div>

app/views/home/index.html.erb
<div class="container">
    <div class="mb-4">
      <h2>Public Recipes</h2>
    </div>
    
      <% @recipes.each do |recipe|%>
        <%= link_to controller: 'recipes', action: 'show', id: recipe.id do %>
          <div class="card  p-4 mb-3" >
            <div class="row">
              <div class="col-md-4">
                <h4><%= recipe.name %></h4>

                <span>By: <%= recipe.user.name %></span>
              </div>
               <div class="col-md-8">
                  <h6>Total food items: <%= recipe.recipe_foods.count %></h6>
                  <h6>Total price: $<%= recipe.recipe_foods.map { |rf| rf.food.price * rf.quantity }.sum %>
                  </h6>
               </div>
            </div>
          </div>
        <% end %>
      <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SweetRecipe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "shared/navigation" %> 


      <main class="main">
        <div class="container"> 

          <% if notice %>
            <p class="notice"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert"><%= alert %></p>
          <% end %>
          <%= yield %>
        </div>
      </main>
  </body>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</html>

app/views/recipe_foods/new.html.erb
<div class="container">
     
     <h2 class="mb-4">New ingredient (<%= @recipe.name %>)</h2>



        <%= form_with model: @recipe_food, url: recipe_foods_path(@recipe), class: "form" do |f| %>
                <div class="row">
                  <div class="col-md-7 mb-3">
                    <div class="form-group">
                        <%= f.label :food_id %><br />
                        <%= f.collection_select(:food_id, Food.where(user_id: current_user.id).order(:name), :id, :name, { prompt: 'Please select a food' }, { class: 'form-control form-control-lg' }) %>      
                    </div>
                  </div>
                </div>


                <div class="row">
                    <div class="col-md-7 mb-3">
                        <div class="form-group">
                            <%= f.label :quantity %><br />
                            <%= f.number_field :quantity, autofocus: true, autocomplete: "quantity",  class: "form-control form-control-lg" %>
                        </div>
                    </div>
                </div>

               
                <div class="actions py-4">
                  <%= f.submit 'Submit', class: 'btn btn-primary' %>
                </div>
        <% end %>
                    
   
  </div>

app/views/recipes/index.html.erb
<div class="container">
    <div class="d-flex justify-content-between items-center mb-4">
      <h2>Recipes</h2>
      <%= link_to 'Add New Recipe', new_recipe_path, class: 'btn btn-primary' %>
    </div>
    
      <% @recipes.each do |recipe|%>
     <%= link_to controller: 'recipes', action: 'show', id: recipe.id do %>
          <div class="card  p-4 mb-3" >
            <div class="row">
              <div class="col-md-4">
                <h4><%= recipe.name %></h4>
              </div>
               <div class="col-md-8">
                  <h4><%= recipe.description %></h4>
               </div>
            </div>
            <hr/>

          <% if current_user.id  === recipe.user_id %>
            <%= link_to 'Delete Recipe', recipe_path(recipe), data: {turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this recipe?'} %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/recipes/new.html.erb
<div class="container">
     
     <h2 class="mb-4">New Recipe</h2>

        <%= form_with model: @recipe, url: recipes_path, class: "form" do |f| %>
                <div class="row">
                  <div class="col-md-7 mb-3">
                    <div class="form-group">
                      <%= f.label :name %><br />
                      <%= f.text_field :name, autofocus: true, autocomplete: "name",  class: "form-control form-control-lg" %>
                    </div>
                  </div>
                </div>


                <div class="row">
                  <div class="col-md-7 mb-3">

                        <div class="row">
                  <div class="col-md-6 mb-3">
                    <div class="form-group">
                      <%= f.label :preparation_time %><br />
                      <%= f.text_field :preparation_time, autofocus: true, autocomplete: "preparation_time",  class: "form-control form-control-lg" %>
                    </div>
                  </div>

                  <div class="col-md-6 mb-3">
                    <div class="form-group">
                      <%= f.label :cooking_time %><br />
                      <%= f.text_field :cooking_time, autofocus: true, autocomplete: "cooking_time",  class: "form-control form-control-lg" %>
                    </div>
                  </div>
                </div>
                </div>
                </div>

                

                <div class="row">
                  <div class="col-md-7 mb-3">
                    <div class="form-group">
                      <%= f.label :description %><br />
                      <%= f.text_area :description, autofocus: true, autocomplete: "description",  class: "form-control form-control-lg" %>
                    </div>
                  </div>
                </div>
                
                <div class="actions py-4">
                  <%= f.submit 'Submit', class: 'btn btn-primary' %>
                </div>
        <% end %>
                    
   
  </div>

app/views/recipes/show.html.erb
<div class="container">
     
     <h2 class="mb-4"><%= @recipe.name %></h2>

        <p><%= @recipe.description %></p>

        <div class="d-flex justify-content-between align-items-start py-4">

            <div>
                <h5>Preparation Time: <b><%= @recipe.preparation_time %> hour</b></h5>
                <h5>Cooking Time: <b><%= @recipe.cooking_time %> hour</b></h5>
            </div>

            <div>
             <% if current_user.id  === @recipe.user_id %>
                <%= form_with model: @recipe, method: :patch,  data: { url: toggle_public_recipe_path(@recipe), recipe_id: @recipe.id } do |form| %>
                    <div class="switch">
                        <input class="" type="checkbox" <%= 'checked' if @recipe.public %> onchange="toggleRecipePublic(this)">
                    </div>
                <% end %>
                <% end %>
            </div>
        </div>

    

        <div class="d-flex justify-content-between align-items-center border-bottom border-top py-2 mt-3">
          <% if current_user.id  === @recipe.user_id %>
            <%= link_to "Generate shopping List", generate_shopping_lists_path(recipe_id: @recipe.id), class: 'btn btn-primary' %>
            <%= link_to "Add ingredient",  new_recipe_recipe_food_path(@recipe.id), class: 'btn btn-primary' %>
          <% end %>
        </div>

        <table class="table table-bordered table-striped table-hover">
            <thead>
                <th>Food</th>
                <th>Quantity</th>
                <th>Value</th>
                <th>Actions</th>
            </thead>

            <tbody>
            
            <% @recipe.recipe_foods.each do |recipe_food|%>
             <tr class="">
    
      <td><%= recipe_food.food.name %></td>
      <td ><%= recipe_food.quantity %></td>
      <td><%= recipe_food.total_price %></td>
      <td>
        <% if current_user.id  === @recipe.user_id %>
          <%= link_to 'Remove', recipe_recipe_food_path(recipe_id: @recipe.id, id: recipe_food.id), data: {turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this Ingredient?'}, class: 'btn btn-primary' %>
        <% end %>

      </td>
      
    </tr>

    <% end %>
            
            </tbody>
        </table>

     </div>

     <script>
  function toggleRecipePublic(checkbox) {
    console.log("called");
    var form = checkbox.closest("form");
    var recipeId = form.dataset.recipeId;
    var url = form.dataset.url;

    var formData = new FormData();
    formData.append("recipe_id", recipeId);

    fetch(url, {
      method: "PATCH",
      body: formData,
      headers: {
        "X-CSRF-Token": document.querySelector("meta[name=csrf-token]").content
      }
    })
      .then(response => response.json())
      .then(data => {
      })
      .catch(error => {
        // Handle errors if any
        console.error(error);
      });
  }
</script>

app/views/shared/_navigation.html.erb
    <nav class="navbar navbar-default navbar-expand-lg fixed-top">
    <div class="container">
     
      <a class="navbar-brand text-brand" href="/">Sweet<span class="color-b">Recipe</span></a>

      <div class="navbar-collapse collapse justify-content-center" id="navbarDefault">
        <ul class="navbar-nav">

          <% if user_signed_in? %>

          <li class="nav-item">
          <%= link_to 'Foods', foods_path, class: 'nav-link' %>
         </li>


            <li class="nav-item">
              <%= link_to 'Recipes', recipes_path, class: 'nav-link' %>
            </li>

            <li class="nav-item">

                 <%= link_to 'Logout', destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this recipe?'}, class: 'nav-link' %>
            </li>
          <% else %>

          <li class="nav-item"> 
              <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>


            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
            </li>


          <% end %>

        </ul>
      </div>


    </div>
  </nav>

app/views/shopping_lists/index.html.erb
<% if @items_to_buy != 0 %>
     <h2 class="mb-4">Shopping Cart</h2>
     <div class="d-flex justify-content-between align-items-start py-4">
        <div>
        <h4>Amount of food items to buy: <%= @shopping_list.length %></h4>
        <h4>Total value of food needed: $<%= @total_amount %></h4>
        </div>

        <div>

            <h4>Recipe: <%= link_to controller: 'recipes', action: 'show', id: @recipe.id do %>
               <%=  @recipe.name %>
                <% end %>
            </h4>
        </div>
     </div>

    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th>Food</th>
                <th>Quantity</th>
                <th>Price($)</th>
            </tr>
        </thead>
        <tbody>
                       <% @shopping_list.each do |food| %>
                            <tr>
                                <th><%= food['name'] %></th>
                                <th><%= food['quantity'] %></th>
                                <th><%= food['price'] %></th>
                            </tr>
                     <% end %>
                    </tbody>
                </table>
    <% else %>
        <div class="text-center">
            <p>Kindly go to a recipe to generate a shopping list.</p>
        </div>
    <% end %>